First pass files api for docker
FlowFuse/driver-docker pull request #108
Opened 2024-08-16 15:29 UTC by hardillb

## Description

Adds the driver interface to https://github.com/FlowFuse/nr-launcher/issues/273

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-08-19 13:17 UTC, hardillb commented
@Steve-Mcl Like k8s, please review but not merge

2024-08-19 13:17 UTC, hardillb commented
Localfs for comparison https://github.com/FlowFuse/driver-localfs/pull/144

2024-08-22 09:18 UTC, Steve-Mcl requested changes

2024-08-22 09:18 UTC, Steve-Mcl commented on docker.js
> +    return `http://${project.id}:2880/flowforge/files_/${filePath}`
should that be `/_/`?

2024-08-22 09:18 UTC, Steve-Mcl commented on docker.js
> +    return `http://${project.id}:2880/flowforge/files_/${filePath}`
```suggestion
const getStaticFileUrl = async (instance, filePath) => {
    return `http://${instance.id}:2880/flowforge/files_/${filePath}`
```

keep with instance naming as in other new functions.

2024-08-22 09:47 UTC, hardillb commented on docker.js
> +    return `http://${project.id}:2880/flowforge/files_/${filePath}`
I had fixed this but not pushed it

2024-08-28 09:19 UTC, Steve-Mcl approved these changes

2024-08-28 10:41 UTC, merged